# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: a3.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x61\x33.proto\"\x8a\x01\n\x04\x42ook\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12 \n\x05genre\x18\x04 \x01(\x0e\x32\x11.Book.genre_types\x12\x0c\n\x04year\x18\x05 \x01(\x05\"%\n\x0bgenre_types\x12\x0b\n\x07\x66iction\x10\x00\x12\t\n\x05novel\x10\x01\"\x1a\n\nIdentifier\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\"\x88\x01\n\x0fGetBookResponse\x12*\n\x06status\x18\x01 \x01(\x0e\x32\x1a.GetBookResponse.ret_value\x12\x13\n\x02\x62k\x18\x02 \x01(\x0b\x32\x05.BookH\x00\x12\r\n\x03msg\x18\x03 \x01(\tH\x00\"\x1e\n\tret_value\x12\x06\n\x02ok\x10\x00\x12\t\n\x05\x65rror\x10\x01\x42\x05\n\x03obj\"t\n\x12\x43reateBookResponse\x12-\n\x06status\x18\x01 \x01(\x0e\x32\x1d.CreateBookResponse.ret_value\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1e\n\tret_value\x12\x06\n\x02ok\x10\x00\x12\t\n\x05\x65rror\x10\x01\"\x91\x01\n\rInventoryItem\x12\x0e\n\x06number\x18\x01 \x01(\x05\x12\x13\n\x02\x62k\x18\x02 \x01(\x0b\x32\x05.BookH\x00\x12*\n\x06status\x18\x03 \x01(\x0e\x32\x1a.InventoryItem.book_status\"\'\n\x0b\x62ook_status\x12\r\n\tavailable\x10\x00\x12\t\n\x05taken\x10\x01\x42\x06\n\x04\x62ook2j\n\x10InventoryService\x12*\n\nCreateBook\x12\x05.Book\x1a\x13.CreateBookResponse\"\x00\x12*\n\x07GetBook\x12\x0b.Identifier\x1a\x10.GetBookResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'a3_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOK._serialized_start=13
  _BOOK._serialized_end=151
  _BOOK_GENRE_TYPES._serialized_start=114
  _BOOK_GENRE_TYPES._serialized_end=151
  _IDENTIFIER._serialized_start=153
  _IDENTIFIER._serialized_end=179
  _GETBOOKRESPONSE._serialized_start=182
  _GETBOOKRESPONSE._serialized_end=318
  _GETBOOKRESPONSE_RET_VALUE._serialized_start=281
  _GETBOOKRESPONSE_RET_VALUE._serialized_end=311
  _CREATEBOOKRESPONSE._serialized_start=320
  _CREATEBOOKRESPONSE._serialized_end=436
  _CREATEBOOKRESPONSE_RET_VALUE._serialized_start=281
  _CREATEBOOKRESPONSE_RET_VALUE._serialized_end=311
  _INVENTORYITEM._serialized_start=439
  _INVENTORYITEM._serialized_end=584
  _INVENTORYITEM_BOOK_STATUS._serialized_start=537
  _INVENTORYITEM_BOOK_STATUS._serialized_end=576
  _INVENTORYSERVICE._serialized_start=586
  _INVENTORYSERVICE._serialized_end=692
# @@protoc_insertion_point(module_scope)
